---
development:
  cloud_name: dyk6yy09j
  api_key: ENV['CLOUD_KEY']
  api_secret: ENV['CLOUD_SECRET']
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: dyk6yy09j
  api_key: ENV['CLOUD_KEY']
  api_secret: ENV['CLOUD_SECRET']
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: dyk6yy09j
  api_key: ENV['CLOUD_KEY']
  api_secret: ENV['CLOUD_SECRET']
  enhance_image_tag: true
  static_image_support: false
